server:
  port: 8088

spring:
  datasource:
    username: root
    password: Xxx10086
    url: jdbc:mysql://114.132.247.49:3306/VectorPractice?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.vec.practicalexercise.entity

#showSql
logging:
  level:
    com:
      example:
        mapper : debug